### PR TITLE
Feat/configure dhcp

### PR DESCRIPTION
**Pull request by morremeyer**
This splits the DHCP service into its own service resource and moves the configuration to `serviceDhcp`.

**This is a breaking change for configurations that do not run the `serviceDns` default values.**

This PR already includes the changes from #153 and should be merged after #153.

### CODE REVIEW

**Comment by MoJo2600** [comment]
Hello, sorry for the delay. Would you please rebase your commit to the latest master. I will merge your change afterwards.

**Comment by morremeyer** [comment]
@MoJo2600 No worries! Branch is rebased now.

**Review by MoJo2600 — APPROVED** [review]
LGTM!

**Comment by MoJo2600** [comment]
I will merge this now. Please stay with me to help resolve any issues that may arise for the users during upgrade :)

**Comment by morremeyer** [comment]
> Please stay with me to help resolve any issues that may arise for the users during upgrade :)

Of course! Just mention me in any issues if needed.

**Pull request merged**
