### PR TITLE
Add chart repo

### PR DESCRIPTION
**Pull request by luqasn**
First off thanks for sharing your pihole setup!

It works very well, I use it together with MetalLB 0.8.1 with no issues.

I am using k3s at home and deploy stuff using a helm operator, but for that I need a helm repo url and your project does not provide one. I forked your repo, set up GitHub pages and used the steps I added to the README to publish 0.1.2 to it.

Please be aware that this puts the release `tar.gz`s under version control for simplicity's sake. A maybe cleaner approach would be to upload the `tar.gz` to releases and then put the url in the `index.yaml`. Do you think this is an issue?

If you want to follow my idea, merge this and activate github pages for the master branch.

### CODE REVIEW

**Comment by MoJo2600** [comment]
The url is https://mojo2600.github.io/pihole-kubernetes/index.yaml

**Comment by luqasn** [comment]
Thanks! An official helm chart would be great too. Thanks again for your work!

**Comment by billimek** [comment]
@MoJo2600, regarding adding the chart to the https://github.com/helm/charts repo, you may want to reconsider:  The maintainers are pushing for people to self-host chart repos and instead add them to helm hub (https://hub.helm.sh/).  It's also worth noting that getting an official helm/charts repo person to respond to the initial pull requests can take weeks.  If you go this route, make sure that you have at least two responsive folks in an `OWNERS` file for the chart.  Trust me on this! :)

Regarding CI and chart self-publishing, if you want to add more to the process, there is an excellent [chart tester](https://github.com/helm/chart-testing) for linting charts and ensuring that changes are valid.  Furthermore it is possible to run [kind](https://github.com/kubernetes-sigs/kind) as part of a CI process where it will actually spin-up a tiny k8s 'cluster' and install the changed chart to ensure that it installs properly.

I have a circleCI example of all the above workflow in my chart repo here if you want to take a look: https://github.com/billimek/billimek-charts/tree/master/.circleci (will probably move to github actions at some point soon)

**Comment by MoJo2600** [comment]
@billimek Thanks for that very helpful information! I have absolutely no experience in maintaining a helm chart. So i think i will follow your advice and publish the chart repo to helm hub.
I will definitely have a look into your ci/cd chain. It seems like more and more people are using this chart and i don't want to break something by accident. Thanks a lot!

**Pull request merged**
