### PR TITLE
fix! Update apiVersion to apps/v1

### LINKED ISSUE #13: Deployment apps/v1beta2 is deprecated in 1.16
Installing on a v1.16 cluster yields `no matches for kind "Deployment" in version "apps/v1beta2"`

appsv1 was introduced in 1.9 as stable

### PR DESCRIPTION
**Pull request by tdorsey**
apps/v1 was introduced in 1.9, v1beta2 has been deprecated in 1.16

BREAKING CHANGE: Cluster versions prior to 1.9 will no longer be supported

Fixes #13

### CODE REVIEW

**Comment by billimek** [comment]
Can you please bump the chart version in Chart.yaml?

As this is a breaking change, should the major version be bumped?

**Comment by tdorsey** [comment]
@billimek Bumped the major version to 1.0.0, but with the other fix at 0.1.3, you might want this one last to avoid having to immediately going to 1.0.1. Can do whichever you prefer

**Comment by MoJo2600** [comment]
I merged the fix for liveness/readyness probes and I think it makes sense to bump the major version for this one.

**Comment by tdorsey** [comment]
Done. New version is 1.0.0

**Comment by MoJo2600** [comment]
Thank you for your work @tdorsey !

**Pull request merged**
