### PR TITLE
Merge TCP and UDP services into one

### PR DESCRIPTION
**Pull request by brnl**
As discussed in #78. This PR merges the two TCP and UDP services into a single service.

### CODE REVIEW

**Comment by brnl** [comment]
Updated the PR commit with a bugfix: I had a duplicate port-name client-udp.
Also I made the DHCP support optional (enabled by default).

**Review by MoJo2600 — COMMENTED** [review]
Thank you, LGTM - But is this a breaking change? So maybe we should move to 1.8 for this if users have to update their configuration.

**Comment by brnl** [comment]
Indeed a major version bump sounds logical to me. I don't know what would be breaking. I've see issue #4 where there was some one having trouble with running TCP and UDP over the same port on metalLB but I don't have experience with metalLB. Do you know more about that?

**Comment by brnl** [comment]
Nope, this is not going to work. Mixed protocols are not going to work with Service type LoadBalancer:

> Error: UPGRADE FAILED: cannot patch "pihole-tcp" with kind Service: Service "pihole-tcp" is invalid: spec.ports: Invalid value: []core.ServicePort{core.ServicePort{Name:"http", Protocol:"TCP", AppProtocol:(*string)(nil), Port:80, TargetPort:intstr.IntOrString{Type:1, IntVal:0, StrVal:"http"}, NodePort:0}, core.ServicePort{Name:"https", Protocol:"TCP", AppProtocol:(*string)(nil), Port:443, TargetPort:intstr.IntOrString{Type:1, IntVal:0, StrVal:"https"}, NodePort:0}, core.ServicePort{Name:"dns", Protocol:"TCP", AppProtocol:(*string)(nil), Port:53, TargetPort:intstr.IntOrString{Type:1, IntVal:0, StrVal:"dns"}, NodePort:0}, core.ServicePort{Name:"dns-udp", Protocol:"UDP", AppProtocol:(*string)(nil), Port:53, TargetPort:intstr.IntOrString{Type:1, IntVal:0, StrVal:"dns-udp"}, NodePort:0}}: **cannot create an external load balancer with mix protocols**   

Also in the MetalLB documentation: [IP address sharing](https://metallb.universe.tf/usage/#ip-address-sharing
):
> [Kubernetes does not currently allow multiprotocol LoadBalancer services](https://github.com/kubernetes/kubernetes/issues/23880). This would normally make it impossible to run services like DNS, because they have to listen on both TCP and UDP. To work around this limitation of Kubernetes with MetalLB, create two services (one for TCP, one for UDP), both with the same pod selector. Then, give them the same sharing key and spec.loadBalancerIP to colocate the TCP and UDP serving ports on the same IP address.

**Pull request closed without merging**
