### PR TITLE
Added option to override password secret

### PR DESCRIPTION
**Pull request by imle**
Instead of setting a password in the values.yaml directly, now you have the option to use something like sealed secrets.

### CODE REVIEW

**Comment by imle** [comment]
I should also note that this is adapted from how the grafana chart performs the same action.

**Comment by billimek** [comment]
@imle do you mind bumping the minor version for this change (e.g. to `1.3.0`)?

**Comment by imle** [comment]
@billimek done!

**Comment by imle** [comment]
@billimek Ah! I missed the readme version mention. Want me to put in another PR or alter this one?

**Comment by MoJo2600** [comment]
I will update the readme. No worries. I'm planning to add it to the ci/cd chain anyway :)

**Pull request merged**
