### PR TITLE
feat: make port of DNS service configurable

### PR DESCRIPTION
**Pull request by morremeyer**
This is desirable when e.g. running pihole on k3s with a service of type LoadBalancer to not collide with the nodes DNS as both a LoadBalancer service and a NodePort on port 53 would collide with `systemd-resolved`s stub resolver when using e.g. Ubuntu.

### CODE REVIEW

**Comment by MoJo2600** [comment]
Thank you! Is this a breaking change? I don't think so, so we could set the version to 1.8.37. And could you please regenerate the Readme with helm-docs?

There is currently a problem with the chart release workflow I have to fix next week. Then I will be able to release your change.

**Comment by morremeyer** [comment]
No, its deliberately backwards-compatible and just makes the default configurable.

Will regenerate the docs later and let you know about it once done.

**Comment by morremeyer** [comment]
@MoJo2600 I updated the documentation. `helm-docs` 1.5.0 seems to have removed the „generated with“ hint.

I left the version number at `1.9.0` as it is an update which adds functionality in a backwards compatible manner as per [Semver 2.0.0](https://semver.org/spec/v2.0.0.html#summary).

**Comment by MoJo2600** [comment]
I'm okay with that.

**Pull request merged**
