### PR TITLE
Liveness- and Readinessprobes checked wrong path

### PR DESCRIPTION
**Pull request by MoJo2600**
Switched path to /admin

Signed-off-by: mojo2600 <christian.erhardt@mojo2k.de>

### CODE REVIEW

**Comment by MoJo2600** [comment]
issue #147

**Comment by propyless** [comment]
Its working for me.. but the url is still wrong I guess.

image
but i guess it works because it gives a return code of 200.
image

**Comment by MoJo2600** [comment]
Thank you for the screenshot. Because my container was always killed... maybe I do have another issue.

**Comment by pabloromeo** [comment]
I believe with the pihole version 2023.1.1 the current paths on the probes no longer work, meaning: admin.index.php
Current probes fail with a 404 and the Pod is constantly killed.
I think this PR was indeed correct and the URL should be changed to /admin

**Pull request closed without merging**
