### PR TITLE
Add option to disable admin password

### PR DESCRIPTION
**Pull request by thegreatsunra**
## What It Does

- Adds an option `disablePassword` to `values.yaml` that, if true, will set the Pi-hole admin password to `""` thus disabling it.

## Related Issue

Resolves: https://github.com/MoJo2600/pihole-kubernetes/issues/251

### CODE REVIEW

**Comment by thegreatsunra** [comment]
Noted the [failure in the latest workflow run](https://github.com/MoJo2600/pihole-kubernetes/actions/runs/5172459167/jobs/9810542169). Merged in the latest on upstream to bring in the latest up-to-date version.

**Comment by MoJo2600** [comment]
Thank you for your contribution. I tried to make some changes to your PR but I'm not allowed to push to your repository. I put my changes now here: https://github.com/MoJo2600/pihole-kubernetes/tree/feat/no-admin-password

My idea was to not have to introduce a new parameter to the values.yml. Instead it would be possible to have three different ways to set a password:

* `adminPassword:` - Without a value the password would be automatically generated which should be the default - I updated the NOTES.txt to show how to retrieve the password after installation
* `adminPassword: ""` - If you provide an empty string, no password is set at all
* `adminPassword: "yourpassword"` - `yourpassword` will be set to as admin password

Question is, if this is a breaking change to the chart. Because then this change should be added to v3 of this chart. There some more breaking changes that would introduce breaking changes. So this pr would have to wait for the release of v3.

**Comment by thegreatsunra** [comment]
Thank you for the feedback!

> I tried to make some changes to your PR but I'm not allowed to push to your repository.

Ahh, shoot. I thought by ticking `Allowing edits by maintainers` you'd be able to commit directly to the branch, but I suppose not. I've added you as a Collaborator, which might address the issue.

> My idea was to not have to introduce a new parameter to the values.yml

Nice. Your approach is cleaner and would reduce config sprawl, so I'm on board. To your point, it would change the existing behavior of the chart, whereas adding a new `disablePassword` parameter would make it an opt-in change while preserving existing behavior.

If we change the behavior by implementing the approach you suggest, then yeah, this change should roll out with v3.

**Comment by MoJo2600** [comment]
There was a second approach to add a feature to disable the admin password so I merged it. See: https://github.com/MoJo2600/pihole-kubernetes/pull/274 - So I'm closing your pull request. Thank you nonetheless

**Comment by thegreatsunra** [comment]
Good solution! Glad to see this implemented, and thank you! 😊

**Pull request closed without merging**
