### PR TITLE
add support for ingress backwards compatibility

### PR DESCRIPTION
**Pull request by jetersen**
No reason to break compatibility

### CODE REVIEW

**Comment by jetersen** [comment]
please merge #100 first than I would love to add testing for k8s v1.18 and v1.19

**Comment by MoJo2600** [comment]
I have merged #100

**Comment by jetersen** [comment]
not sure why the test fails 😰

**Comment by MoJo2600** [comment]
I'm currently cleaning up. Thank you for your work. 
Closing this PR because the switch to `networking.k8s.io/v1` is in main.

**Pull request closed without merging**
