### PR TITLE
Bumping chart version to trigger CI

### PR DESCRIPTION
**Pull request by billimek**
This will likely result in some linting errors that we can fix as part of this PR

### CODE REVIEW

**Comment by billimek** [comment]
The helm chart install test thing is failing for some reason.  This didn't happen with the ~15 charts in my personal helm repo, not sure why.  For reference [asking for help](https://kubernetes.slack.com/archives/CHK6WB5R8/p1579039588022000) in the helm-chart-testing slack channel.

**Comment by MoJo2600** [comment]
Hm... this is strange... just a guess.. might it have to do with the initialization of the adlists? pihole tries to download the adlists after start and maybe there is an issue during download and the container stops?

**Comment by billimek** [comment]
Determined the issue: The default value for the pihole chart is to use the LoadBalancer service type.  The 'kubernetes-in-docker' (`KIND`) test cluster doesn't support LoadBalancer (just ClusterIP and NodePort), so the helm release eventually times out due to the services never getting an IP from the (missing) LoadBalancer.

I'm checking to see what options we have to work around this.  Initial thoughts are:

* Change the chart defaults to use ClusterIP or NodePort
* Skip the install/test step of CI
* Figure out a way to fake or shim a loadbalancer in the test cluster

**Comment by MoJo2600** [comment]
Nice stuff. Should we merge it then? Next step would be to create a pull request against hub.helm.sh or is there something else todo? Something I'm able to help maybe?

**Pull request merged**
