### PR TITLE
Tweaking probes settings

### LINKED ISSUE #21: LivenessProbe may be too aggressive
Using the current settings I notice that the pihole pods occasionally restart (a few times/day) due to liveness probes failing.

The remedy is to adjust the probe settings to be a little more forgiving.  I'll submit a pull request with those adjustments as well as to make the probe values configurable as values.

### PR DESCRIPTION
**Pull request by billimek**
* Adjust probes settings to make them slightly less aggressive to prevent
unwanted restarts
* Make probes configurable via helm values

Fixes #21

### CODE REVIEW

**Comment by billimek** [comment]
@MoJo2600 this PR for your consideration

**Comment by MoJo2600** [comment]
Thank you! Makes absolute sense.

**Comment by MoJo2600** [comment]
Would it make sense, if i give you maintainer rights for this repo? Then you would be able to merge PR?

**Comment by billimek** [comment]
> Would it make sense, if i give you maintainer rights for this repo? Then you would be able to merge PR?

Sure!  I'd be happy to help out with that!

**Pull request merged**
