### PR TITLE
feat: Add context for other custom dnsmasq settings

### PR DESCRIPTION
**Pull request by johnsondnz**
Adds context settings values for ConfigMap that creates `/etc/dnsmasq.d/02-custom.conf` settings file.

## values
```
dnsmasq:
  customSettings:
    - rebind-domain-ok=/plex.direct/
```

## output
```
apiVersion: v1
data:
  02-custom.conf: |
    addn-hosts=/etc/addn-hosts
    rebind-domain-ok=/plex.direct/
  addn-hosts: ""
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: pihole
    meta.helm.sh/release-namespace: network
  creationTimestamp: "2021-06-12T21:51:48Z"
  labels:
    app: pihole
    app.kubernetes.io/managed-by: Helm
    chart: pihole-1.9.1
    heritage: Helm
    release: pihole
  name: pihole-custom-dnsmasq
  namespace: network
  resourceVersion: "1109840"
  uid: 0c94634b-6942-41a3-94b8-b680929d41ae
```

### CODE REVIEW

**Comment by MoJo2600** [comment]
Thank you! Could you please regenerate the documentation with helm-docs and bump the version?

**Comment by johnsondnz** [comment]
@all-contributors please add @johnsondnz for minor customSettings contribution

**Comment by johnsondnz** [comment]
@all-contributors please add @johnsondnz for minor customSettings contribution

**Comment by johnsondnz** [comment]
should have read the docs :)

@all-contributors please add @johnsondnz for code

**Comment by MoJo2600** [comment]
Thank you!

**Pull request merged**
