### PR TITLE
Support for custom cnames using dnsmasq on pihole

### PR DESCRIPTION
**Pull request by larivierec**
This basically allows us to set custom cname values through the helm chart using the `customCnameEntries`. 
It is related to issue #171 as this was not possible.

### CODE REVIEW

**Comment by larivierec** [comment]
Note: i can probably squash all this before merging unless the process is automatic, let me know.

**Comment by larivierec** [comment]
weird the linter seems to fail however, locally this works just fine

```
==> Linting .

1 chart(s) linted, 0 chart(s) failed
```

**Comment by MoJo2600** [comment]
Thank you for your contribution. There seem to be trailing spaces somewhere. I'm happy to merge the commits when everything is finished.

**Comment by larivierec** [comment]
> Thank you for your contribution. There seem to be trailing spaces somewhere. I'm happy to merge the commits when everything is finished.

I think I have found them

**Comment by MoJo2600** [comment]
Then let's go again!

**Comment by larivierec** [comment]
i enabled them locally in my forked repository to test. it seems to pass with the latest changes, sorry for this

**Pull request closed without merging**
